name: Build and Publish

on:
  workflow_dispatch:



jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Miniforge
        run: |
          curl -L -o Miniforge3-MacOSX-arm64.sh https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh
          bash Miniforge3-MacOSX-arm64.sh -b -p $HOME/miniforge
          echo "export PATH=$HOME/miniforge/bin:$PATH" >> $GITHUB_ENV

      - name: Initialize conda environment for pack.sh
        shell: bash
        run: |
          source $HOME/miniforge/etc/profile.d/conda.sh
          conda activate base

      - name: Test
        run: |
          cd deployment/exe/macos && \
          export PATH=$HOME/miniforge/bin:$PATH && \
          source $HOME/miniforge/etc/profile.d/conda.sh && \
          conda activate base &&\
          chmod +x ./pack.sh &&\
          ./pack.sh &&\
          mkdir raw &&\
          mkdir label &&\
          Biom3d.app/Contents/MacOS/bin/bin/python3.11  -c "
          import numpy as np
          image = np.random.rand(8, 32, 32).astype(np.float32)
          mask = (image > 0.5).astype(np.uint8)
          np.save('raw/1.npy', image)
          np.save('label/1.npy', mask)" &&\
          ls raw &&\
          ls label &&\
          open Biom3d.app &&\
          Biom3d.app/Contents/MacOS/bin/bin/python3.11 -u -m biom3d.preprocess_train --img_dir raw --msk_dir label --num_epochs=1 --desc Unit --num_classes=1 &&\
          ls && ls logs &&\
          echo $(ls logs/*Unit* 2>/dev/null) &&\
          Biom3d.app/Contents/MacOS/bin/bin/python3.11 -u -m biom3d.pred -i raw -l logs/$(ls logs 2>/dev/null) && \
          Biom3d.app/Contents/MacOS/bin/bin/python3.11 -u -c "
          import tkinter as tk
          root = tk.Tk()
          root.title('Test')
          root.geometry('200x100')
          print('Fenêtre créée sans mainloop')
          "



